apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: visionguard-pvc
  namespace: visionguard
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
