apiVersion: v1
kind: Secret
metadata:
  name: visionguard-secrets
  namespace: visionguard
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: "YOUR_TELEGRAM_BOT_TOKEN"
  TELEGRAM_CHAT_ID: "YOUR_TELEGRAM_CHAT_ID"
  CLOUDINARY_URL: "YOUR_CLOUDINARY_URL"
